spring.application.name=ecommerce

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# R2 Storage
storage.endpoint=${STORAGE_ENDPOINT}
storage.access-key=${STORAGE_ACCESS_KEY}
storage.secret-key=${STORAGE_SECRET_KEY}
storage.bucket=${STORAGE_BUCKET:minimoda-images}
storage.public-url=${STORAGE_PUBLIC_URL}

